services:
  postgres:
    image: postgres:16
    container_name: document-api-postgres
    environment:
      POSTGRES_DB: documentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - document-api-postgres-data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:4.1.2
    container_name: document-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  document-api:
    build:
      context: ./document-api
    container_name: document-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DOCUMENT_API_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DOCUMENT_API_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCUMENT_API_DATASOURCE_PASSWORD}

      MAGALU_OBJECT_STORAGE_ENDPOINT: ${MAGALU_OBJECT_STORAGE_ENDPOINT}
      MAGALU_OBJECT_STORAGE_REGION: ${MAGALU_OBJECT_STORAGE_REGION}
      MAGALU_OBJECT_STORAGE_BUCKET: ${MAGALU_OBJECT_STORAGE_BUCKET}
      MAGALU_OBJECT_STORAGE_ACCESS_KEY: ${MAGALU_OBJECT_STORAGE_ACCESS_KEY}
      MAGALU_OBJECT_STORAGE_SECRET_KEY: ${MAGALU_OBJECT_STORAGE_SECRET_KEY}
    depends_on:
      - postgres
      - kafka

  document-processor:
    build:
      context: ./document-processor
    container_name: document-processor
    depends_on:
      - kafka

volumes:
  document-api-postgres-data:
