spring.application.name=document-processor

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.consumer.group-id=document-processor

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties[spring.json.add.type.headers]=false

app.kafka.topics.document-uploaded=document.uploaded.v1
app.kafka.topics.document-processed=document.processed.v1

magalu.object-storage.endpoint=${MAGALU_OBJECT_STORAGE_ENDPOINT}
magalu.object-storage.region=${MAGALU_OBJECT_STORAGE_REGION}
magalu.object-storage.bucket=${MAGALU_OBJECT_STORAGE_BUCKET}
magalu.object-storage.access-key=${MAGALU_OBJECT_STORAGE_ACCESS_KEY}
magalu.object-storage.secret-key=${MAGALU_OBJECT_STORAGE_SECRET_KEY}